[theme]
base = "dark"
primaryColor = "#204020" # GM Rainforest Green  
backgroundColor = "#0b1220" 
secondaryBackgroundColor = "#0f1720" 
textColor = "#fff"
font = "sans serif"

[server]
headless = true
port = 8501
